/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BrtTrackingResult, BrtTrackingEvent } from "./types";

export const mockShipments: Record<string, Partial<BrtTrackingResult>> = {
  "08459100301718": {
    success: true,
    code: 0,
    severity: "INFO",
    codeDesc: "Spedizione consegnata con successo",
    message: "La spedizione è stata consegnata.",
    ragione_sociale: "ABATE GIORGIO",
    indirizzo: "VIA FRANCESCO REDI 58",
    cap: "93012",
    localita: "GELA",
    sigla_provincia: "CL",
    sigla_nazione: "IT",
    referente_consegna: "ABATE GIORGIO",
    telefono_referente: "+393495806585",
    note_consegna: ["Consegnare al piano terra", "Chiamare prima della consegna"],

    // Mittente details
    ragione_sociale_mittente: "ARLIA SRL",
    indirizzo_mittente: "VIA FRAILLITI SNC",
    cap_mittente: "87030",
    localita_mittente: "LONGOBARDI",
    sigla_provincia_mittente: "CS",
    sigla_nazione_mittente: "IT",
    telefono_mittente: "+39098278131",

    colli: 1,
    peso_kg: 0,
    dimensione_info: "Dimensione non disponibile",
    peso_info: "Peso non disponibile",
    nota_info: "328 - -",

    riferimento_mittente_numerico: 88151,
    riferimento_mittente_alfabetico: "brt-marco2",
    
    data_cons_richiesta: "16.06.2026",
    ora_cons_richiesta: "Qualsiasi ora",
    tipo_cons_richiesta: "Standard",
    descrizione_cons_richiesta: "Nessun vincolo inserito",
    data_teorica_consegna: "16.06.2026",
    ora_teorica_consegna_da: "08:30",
    ora_teorica_consegna_a: "18:30",
    data_consegna_merce: "16.06.2026",
    ora_consegna_merce: "15:40",
    firmatario_consegna: "ABATE GIORGIO",
    stato_sped_parte1: "CONSEGNATA",
    stato_sped_parte2: "OK",
    descrizione_stato_sped_parte1: "Spedizione consegnata con successo",
    descrizione_stato_sped_parte2: "Consegnata",
    lista_eventi: [
      { data: "16.06.2026", ora: "18:47:25", id: "POD", descrizione: "Abbiamo ricevuto la prova di consegna", filiale: "" },
      { data: "16.06.2026", ora: "15:40:10", id: "DEL", descrizione: "La spedizione è stata consegnata", filiale: "Caltanissetta, IT" },
      { data: "16.06.2026", ora: "10:39:59", id: "O4D", descrizione: "La spedizione è in consegna", filiale: "Caltanissetta, IT" },
      { data: "16.06.2026", ora: "08:32:45", id: "ARR", descrizione: "La spedizione è presso la filiale di consegna", filiale: "Caltanissetta, IT" }
    ]
  },
  "BRT-OK-CONSEGNATO": {
    success: true,
    code: 0,
    severity: "INFO",
    codeDesc: "Spedizione consegnata con successo",
    message: "La spedizione è stata recapitata al destinatario.",
    ragione_sociale: "Rossi & Associati S.r.l.",
    indirizzo: "Via Alessandro Manzoni, 45",
    cap: "20121",
    localita: "Milano",
    sigla_provincia: "MI",
    sigla_nazione: "IT",
    referente_consegna: "Sig. Mario Rossi",
    telefono_referente: "+39 347 1234567",
    colli: 3,
    peso_kg: 24.5,
    riferimento_mittente_numerico: 859402,
    riferimento_mittente_alfabetico: "ORD-2026-993",
    data_cons_richiesta: "2026-06-15",
    ora_cons_richiesta: "09:00",
    tipo_cons_richiesta: "TASSATIVA",
    descrizione_cons_richiesta: "Consegnare tassativamente entro le ore 12:00",
    data_teorica_consegna: "2026-06-16",
    ora_teorica_consegna_da: "09:30",
    ora_teorica_consegna_a: "11:30",
    data_consegna_merce: "2026-06-16",
    ora_consegna_merce: "10:14",
    firmatario_consegna: "Rossi Mario (Firma Digitale)",
    stato_sped_parte1: "CONSEGNATA",
    stato_sped_parte2: "OK",
    descrizione_stato_sped_parte1: "Spedizione regolarmente consegnata",
    descrizione_stato_sped_parte2: "Esito positivo",
    lista_eventi: [
      { data: "2026-06-16", ora: "10:14", id: "DEL", descrizione: "CONSEGNATA CON SUCCESSO", filiale: "MILANO CENTRALE" },
      { data: "2026-06-16", ora: "08:15", id: "O4D", descrizione: "IN CONSEGNA CON AUTISTA", filiale: "MILANO CENTRALE" },
      { data: "2026-06-16", ora: "04:30", id: "ARR", descrizione: "ARRIVATA IN FILIALE DI DESTINAZIONE", filiale: "MILANO CENTRALE" },
      { data: "2026-06-15", ora: "22:15", id: "HUB", descrizione: "IN TRANSITO PRESSO HUB DI SCAMBIO", filiale: "BOLOGNA HUB" },
      { data: "2026-06-15", ora: "18:40", id: "DEP", descrizione: "PARTITA DALLA FILIALE DI ORIGINE", filiale: "ROMA TIBURTINA" },
      { data: "2026-06-15", ora: "15:00", id: "PUG", descrizione: "SPEDIZIONE PRELEVATA PRESSO IL MITTENTE", filiale: "ROMA TIBURTINA" }
    ]
  },
  "BRT-IN-TRANSIT": {
    success: true,
    code: 0,
    severity: "INFO",
    codeDesc: "Spedizione in transito",
    message: "La merce è attualmente in viaggio verso la filiale di destinazione.",
    ragione_sociale: "TechStore Italia di Sofia Bianchi",
    indirizzo: "Viale della Repubblica, 112",
    cap: "50129",
    localita: "Firenze",
    sigla_provincia: "FI",
    sigla_nazione: "IT",
    referente_consegna: "Sofia Bianchi",
    telefono_referente: "+39 055 987654",
    colli: 1,
    peso_kg: 5.2,
    riferimento_mittente_numerico: 748102,
    riferimento_mittente_alfabetico: "AMZ-FLOR-98",
    data_cons_richiesta: "2026-06-17",
    ora_cons_richiesta: "14:00",
    tipo_cons_richiesta: "standard",
    descrizione_cons_richiesta: "",
    data_teorica_consegna: "2026-06-18",
    ora_teorica_consegna_da: "14:00",
    ora_teorica_consegna_a: "18:00",
    data_consegna_merce: "",
    ora_consegna_merce: "",
    firmatario_consegna: "",
    stato_sped_parte1: "IN VIAGGIO",
    stato_sped_parte2: "REGOLARE",
    descrizione_stato_sped_parte1: "In transito verso l'hub di destinazione",
    descrizione_stato_sped_parte2: "In orario",
    lista_eventi: [
      { data: "2026-06-17", ora: "02:10", id: "HUB", descrizione: "IN TRANSITO PRESSO HUB DI SCAMBIO", filiale: "BOLOGNA HUB" },
      { data: "2026-06-16", ora: "19:30", id: "DEP", descrizione: "PARTITA DALLA FILIALE DI ORIGINE", filiale: "TORINO LINOTTO" },
      { data: "2026-06-16", ora: "16:15", id: "PUG", descrizione: "SPEDIZIONE ACCETTATA PRESSO IL CENTRO BRT", filiale: "TORINO LINOTTO" }
    ]
  },
  "BRT-GIACENZA": {
    success: true,
    code: 0,
    severity: "WARNING",
    codeDesc: "Spedizione in giacenza per destinatario assente",
    message: "Giacenza aperta. Sarà effettuato un nuovo tentativo o attesa istruzione dal mittente.",
    ragione_sociale: "EcoDesign di Luca Verdi",
    indirizzo: "Corso Vittorio Emanuele II, 88",
    cap: "80121",
    localita: "Napoli",
    sigla_provincia: "NA",
    sigla_nazione: "IT",
    referente_consegna: "Corrado Verdi",
    telefono_referente: "+39 081 765432",
    colli: 6,
    peso_kg: 84.0,
    riferimento_mittente_numerico: 304918,
    riferimento_mittente_alfabetico: "FURNITURE-NAP-A",
    data_cons_richiesta: "",
    ora_cons_richiesta: "",
    tipo_cons_richiesta: "",
    descrizione_cons_richiesta: "",
    data_teorica_consegna: "2026-06-16",
    ora_teorica_consegna_da: "09:00",
    ora_teorica_consegna_a: "13:00",
    data_consegna_merce: "",
    ora_consegna_merce: "",
    firmatario_consegna: "",
    stato_sped_parte1: "IN GIACENZA",
    stato_sped_parte2: "DESTINATARIO ASSENTE",
    descrizione_stato_sped_parte1: "In giacenza presso la filiale di destinazione",
    descrizione_stato_sped_parte2: "Tentativo effettuato, destinatario assente",
    lista_eventi: [
      { data: "2026-06-16", ora: "17:30", id: "GIA", descrizione: "APERTURA DOSSIER DI GIACENZA IN FILIALE", filiale: "NAPOLI PORTICI" },
      { data: "2026-06-16", ora: "11:45", id: "ABS", descrizione: "DESTINATARIO CHIAMATO MA NON REPERIBILE (LASCIATO AVVISO)", filiale: "NAPOLI PORTICI" },
      { data: "2026-06-16", ora: "07:45", id: "O4D", descrizione: "IN CONSEGNA CON AUTISTA", filiale: "NAPOLI PORTICI" },
      { data: "2026-06-16", ora: "05:10", id: "ARR", descrizione: "ARRIVATA IN FILIALE DI DESTINAZIONE", filiale: "NAPOLI PORTICI" },
      { data: "2026-06-15", ora: "22:00", id: "HUB", descrizione: "IN TRANSITO PRESSO HUB DI SCAMBIO", filiale: "BOLOGNA HUB" },
      { data: "2026-06-15", ora: "17:15", id: "DEP", descrizione: "PARTITA DALLA FILIALE DI ORIGINE", filiale: "PISA CENTRO" }
    ]
  },
  "BRT-ERROR": {
    success: false,
    code: -12,
    severity: "ERROR",
    codeDesc: "SPEDIZIONE NON TROVATA",
    message: "Il segnacollo inserito non corrisponde a nessuna spedizione attiva nei nostri sistemi.",
    ragione_sociale: "",
    indirizzo: "",
    cap: "",
    localita: "",
    sigla_provincia: "",
    sigla_nazione: "",
    referente_consegna: "",
    telefono_referente: "",
    colli: 0,
    peso_kg: 0,
    riferimento_mittente_numerico: 0,
    riferimento_mittente_alfabetico: "",
    data_cons_richiesta: "",
    ora_cons_richiesta: "",
    tipo_cons_richiesta: "",
    descrizione_cons_richiesta: "",
    data_teorica_consegna: "",
    ora_teorica_consegna_da: "",
    ora_teorica_consegna_a: "",
    data_consegna_merce: "",
    ora_consegna_merce: "",
    firmatario_consegna: "",
    lista_eventi: []
  }
};

export function generateFallbackTracking(parcelID: string): BrtTrackingResult {
  const normId = parcelID.toUpperCase().trim();
  
  if (mockShipments[normId]) {
    return {
      parcelID,
      ...(mockShipments[normId] as BrtTrackingResult)
    };
  }

  // Generate a realistic dynamic mock response based on the formatting of the parcel ID
  // simple checks to give nice data variety
  const isDelivered = normId.startsWith("BRT") || normId.length % 2 === 0;
  const isTransit = normId.includes("TR") || normId.length % 3 === 1;

  if (isDelivered) {
    return {
      parcelID,
      success: true,
      code: 0,
      severity: "INFO",
      codeDesc: "Esito Positivo",
      message: "Spedizione recapitata regolarmente.",
      ragione_sociale: `Ditta Automatica SpA (${parcelID})`,
      indirizzo: "Viale dei Ciliegi, 204",
      cap: "00185",
      localita: "Roma",
      sigla_provincia: "RM",
      sigla_nazione: "IT",
      referente_consegna: "Dott. Giovanni Verga",
      telefono_referente: "+39 06 11223344",
      colli: 2,
      peso_kg: 14.8,
      riferimento_mittente_numerico: 554321,
      riferimento_mittente_alfabetico: `DYN-${normId.slice(-4) || 'ABCD'}`,
      data_cons_richiesta: "2026-06-16",
      ora_cons_richiesta: "10:00",
      tipo_cons_richiesta: "standard",
      descrizione_cons_richiesta: "Suonare al civico 10 se cancello principale chiuso",
      data_teorica_consegna: "2026-06-17",
      ora_teorica_consegna_da: "10:00",
      ora_teorica_consegna_a: "12:00",
      data_consegna_merce: "2026-06-17",
      ora_consegna_merce: "11:22",
      firmatario_consegna: "G. Verga (Portineria)",
      stato_sped_parte1: "CONSEGNATA",
      stato_sped_parte2: "OK",
      descrizione_stato_sped_parte1: "Consegnata",
      descrizione_stato_sped_parte2: "Consegna completata",
      lista_eventi: [
        { data: "2026-06-17", ora: "11:22", id: "DEL", descrizione: "MERCE CONSEGNATA CON SUCCESSO", filiale: "ROMA LAURENTINA" },
        { data: "2026-06-17", ora: "07:55", id: "O4D", descrizione: "COLLI IN CONSEGNA CON AUTISTA", filiale: "ROMA LAURENTINA" },
        { data: "2026-06-17", ora: "02:14", id: "ARR", descrizione: "ARRIVATA PRESSO FILIALE DI ARRIVO", filiale: "ROMA LAURENTINA" },
        { data: "2026-06-16", ora: "21:30", id: "HUB", descrizione: "IN VIAGGIO TRA CENTRI OPERATIVI", filiale: "MILANO HUB" },
        { data: "2026-06-16", ora: "18:05", id: "PUG", descrizione: "ACCETTATA E DOCUMENTATA", filiale: "MILANO BOVISA" }
      ]
    };
  } else if (isTransit) {
    return {
      parcelID,
      success: true,
      code: 0,
      severity: "INFO",
      codeDesc: "In Transito",
      message: "ID collo localizzato sulla linea principale di smistamento.",
      ragione_sociale: `Studio Architettura Paladini (${parcelID})`,
      indirizzo: "Piazza Garibaldi, 12",
      cap: "70122",
      localita: "Bari",
      sigla_provincia: "BA",
      sigla_nazione: "IT",
      referente_consegna: "Ing. Paola Paladini",
      telefono_referente: "+39 080 334455",
      colli: 1,
      peso_kg: 3.1,
      riferimento_mittente_numerico: 981240,
      riferimento_mittente_alfabetico: `BRT-SHIP-${normId.slice(-3)}`,
      data_cons_richiesta: "",
      ora_cons_richiesta: "",
      tipo_cons_richiesta: "standard",
      descrizione_cons_richiesta: "",
      data_teorica_consegna: "2026-06-18",
      ora_teorica_consegna_da: "09:00",
      ora_teorica_consegna_a: "18:00",
      data_consegna_merce: "",
      ora_consegna_merce: "",
      firmatario_consegna: "",
      stato_sped_parte1: "IN VIAGGIO",
      stato_sped_parte2: "IN ORARIO",
      descrizione_stato_sped_parte1: "Spedizione in viaggio",
      descrizione_stato_sped_parte2: "Regolare instradamento",
      lista_eventi: [
        { data: "2026-06-17", ora: "04:12", id: "HUB", descrizione: "IN COMMUTAZIONE HUB LOGISTICO", filiale: "ANCONA HUB" },
        { data: "2026-06-16", ora: "19:00", id: "DEP", descrizione: "PARTENZA DA FILIALE ACCETTAZIONE", filiale: "BOLOGNA ROVERI" },
        { data: "2026-06-16", ora: "14:22", id: "PUG", descrizione: "CARICATO ALLA PARTENZA", filiale: "BOLOGNA ROVERI" }
      ]
    };
  } else {
    // Return not found scenario styled nicely as a result
    return {
      parcelID,
      success: false,
      code: -10,
      severity: "ERROR",
      codeDesc: "Spedizione Non Trovata",
      message: `Il segnacollo ${parcelID} non è stato trovato nei sistemi o non è ancora registrato. Verificare la digitazione e riprovare tra qualche minuto.`,
      ragione_sociale: "",
      indirizzo: "",
      cap: "",
      localita: "",
      sigla_provincia: "",
      sigla_nazione: "",
      referente_consegna: "",
      telefono_referente: "",
      colli: 0,
      peso_kg: 0,
      riferimento_mittente_numerico: 0,
      riferimento_mittente_alfabetico: "",
      data_cons_richiesta: "",
      ora_cons_richiesta: "",
      tipo_cons_richiesta: "",
      descrizione_cons_richiesta: "",
      data_teorica_consegna: "",
      ora_teorica_consegna_da: "",
      ora_teorica_consegna_a: "",
      data_consegna_merce: "",
      ora_consegna_merce: "",
      firmatario_consegna: "",
      lista_eventi: []
    };
  }
}
